//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class athlete
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public int country { get; set; }
        public int sport { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string url { get; set; }
    }
}
