//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        public int id { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public int country { get; set; }
        public short year { get; set; }
    }
}
