//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class results1
    {
        public int id { get; set; }
        public int athlete { get; set; }
        public int game { get; set; }
        public int @event { get; set; }
        public int country { get; set; }
        public Nullable<int> medal { get; set; }
        public string result { get; set; }
    }
}
